name:                blog-hakyll-netlify
version:             0.1.0.0
github:              "harfangk/blog-hakyll-netlify"
license:             BSD3
author:              "Bonghyun Kim"
maintainer:          "bonghyun.d.kim@gmail.com"
copyright:           "MIT License"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/harfangk/blog-hakyll-netlify#readme>

dependencies:
- base >= 4.7 && < 5
- apply-refact
- hlint
- stylish-haskell
- hasktags
- hakyll
- hoogle
- filepath
- directory

library:
  source-dirs: []

executables:
  blog-hakyll-netlify-exe:
    main:                site.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-hakyll-netlify
