# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: haskell:8.8.4
    steps:
      - checkout
      - run:
          name: Download and add nodejs apt
          command: "curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -"
      - run:
          name: Install apt packages
          command: "sudo apt-get update && apt-get install -y nodejs"
      - run:
          name: Install netlify-cli
          command: npm install netlify-cli -g
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - dependencies-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run: stack build
      - save_cache:
          name: Cache Dependencies
          key: dependencies-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run: stack exec blog-hakyll-netlify-exe build
      - run:
          name: Deploy
          command: netlify deploy --dir _site/ --prod
workflows:
  version: 2
  build:
    jobs:
      - build
