# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.3.0
jobs:
  build:
    docker:
      - image: haskell:8.8.4
    steps:
      - checkout
      - node/install:
          node-version: 14.16.0
      - run:
          name: Install netlify-cli
          command: npm install --prefix=$HOME/.local --global netlify-cli
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - dependencies-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run: stack build
      - save_cache:
          name: Cache Dependencies
          key: dependencies-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run: stack exec blog-hakyll-netlify-exe build
      - run:
          name: Deploy
          command: netlify deploy --dir _site/ --prod
workflows:
  version: 2
  build:
    jobs:
      - build
